### ISSUE TITLE
Homepage Content

### ISSUE THREAD

**Issue by jonathandavis** [thefatherhoodwing/orion#2]
We need body copy for:

- [x] Home page
- [x] Ops
- [x] FAQ
- [x] Store
- [x] Join
- [x] Social

**Comment by rutgerolthuis** [comment]
**FAQ :** 

Q) What is the Fatherhood Wing.
A) We are a group of like minded individuals who enjoy playing Elite Dangerous. Mother? Father? Person who's not able to play as much due to work commitments? You are all welcome here.

Q) So I've signed up and have joined the Discord channel. What next?
A) Introduce yourself, have a look around and the best thing of all. Ask questions! We have a lot of experienced players across all Elite subjects who are more than happy to lend a hand with any questions you may have.

Q) What is this BGS I see everyone talking about?
A) BGS or BackGround Simulation is they system that is used in game to help The Fatherhood expand throughout the galaxy. It is incredibly detailed and we have many dedicated people working on this. It really adds another layer of immersion into the game. If you feel like it may be something you enjoy, head on over to the BGS section of the discord.

Q) I've had a disagreement with another member of the wing and would like to speak with someone privately about this. 
A) We are lucky enough within this wing that we haven't had to deal with this very much. We have a great group of people who are easy to get along with. However! If there is a problem please feel free to private message any member of the Wing Admin, Wing Command or Operations Officer (You can see them at anytime on the right hand side of discord). Any private message will be discussed within the Wing Command as how best to obtain a satisfactory resolution to any problem.

Q) I freaking love this wing you guys are awesome. I want to get some Merchandise so I can represent the wing. Where can I get this?
A) Awesome!! We're really glad you like us. To be honest, we think you're pretty cool too! As for Merch? This is being worked on along with a website and news of this will be forthcoming soon. Oh wait! This is the website! Looking cool isn't it, even though it's still a work in progress. 

Q) Ok I'm in! Man there's a lot of rooms around on the discord server. 
A) Elite is an in depth game. We do have a lot of rooms but those are split into categories which you can hide to make things a bit less busy.

Q) I have a question about a specific topic, who do I ask?
A) You can ask anyone anything. However, we do have specific rooms set up for each topic. We also have experts that when online you will see separately on the right hand panel of discord.

Q) All this chat is pretty sweet but what do I do if I want to listen to music when I'm playing?
A) We have a couple of options. You can either take a break in our Intergalactic Jukebox room or head to Spotify to listen to our playlists. We have one chilled out playlist https://open.spotify.com/user/xim3keanbomij94jvd76wpldu/playlist/25wkp4UODYGvu43WqmjkNV?si=pxA4IfKfQziNDKgho6NloA
and one that's a bit heavier https://open.spotify.com/user/xim3keanbomij94jvd76wpldu/playlist/07u3WdL1USBEoJdIbWQJLm?si=-f-ZOu6BRXKXXzhXXcHMxg.
